### ISSUE TITLE
band frequency ranges

### ISSUE THREAD

**Issue by upajdosz** [ruta-k/uGMRT-pipeline#1]
Hi!
In ugfunctions.py in def getbandcut(inpmsfile) observer's changes in the frequency ranges (band) (and LO) are not taking into account (e.g. for band 5, 1025-1425 MHz).

**Comment by ruta-k** [comment]
Hi. Thank you for spotting the limitation ! I have fixed it.

**Comment by ruta-k** [comment]
I am closing the issue. thanks.
